### ISSUE TITLE
I have implemented it as well...

### ISSUE THREAD

**Issue by starius** [bungle/lua-resty-tsort#1]
https://github.com/starius/toposort/

**Comment by bungle** [comment]
@starius, damn, I even asked this on lua channel at freenode, and tried to google it.

**Comment by bungle** [comment]
I will add link to your inplementation. It looks great and has a lot more features. I will leave my inplementation there as well as it is simple and stupid.

**Comment by bungle** [comment]
@starius 

I added notes and link to your project:
https://github.com/bungle/lua-resty-tsort#alternatives

I think I can close this now.

Thanks for building such a library, It looks nice.
